# Generated by Django 4.1.4 on 2023-01-30 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediadb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(blank=True, max_length=50, null=True)),
                ('incoming_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_incoming_set', to=settings.AUTH_USER_MODEL)),
                ('outgoing_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_outgoing_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
