# Generated by Django 4.1.4 on 2023-02-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediadb', '0002_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='incoming_msg',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='outgoing_msg',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update_date',
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img_profiles/23/01/profile_default.jpg', upload_to='img_profiles/%y/%m'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FollowUser',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
