# Generated by Django 4.1.4 on 2023-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediadb', '0004_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img_post/%y/%m'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img_profiles/%y/%m'),
        ),
    ]
