# Generated by Django 4.1.4 on 2023-02-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediadb', '0005_alter_post_img_alter_user_cover_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img_profiles/23/01/prolie_default.png', upload_to='img_profiles/%y/%m'),
        ),
    ]
